export const FETCH_HOTBOARDS = "FETCH_HOTBOARDS"
export const FETCH_HOTBOARDS_DONE = "FETCH_HOTBOARDS_DONE"
export const FETCH_HOTBOARDS_ERROR = "FETCH_HOTBOARDS_ERROR"

export const FETCH_POSTSLIST = "FETCH_POSTSLIST"
export const FETCH_POSTSLIST_DONE = "FETCH_POSTSLIST_DONE"
export const FETCH_POSTSLIST_ERROR = "FETCH_POSTSLIST_ERROR"

export const FETCH_POST = "FETCH_POST"
export const FETCH_POST_DONE = "FETCH_POST_DONE"
export const FETCH_POST_ERROR = "FETCH_POST_ERROR"

export const FETCH_CRYPTOCOIN = "FETCH_CRYPTOCOIN"
export const FETCH_CRYPTOCOIN_DONE = "FETCH_CRYPTOCOIN_DONE"